# -*- coding: utf-8 -*-
"""Algos30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VDpkSgt8QizdGRQZEYacjLoqzpG8qz1F
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/auto-mpg.csv")

df.sample(10)

df.info()

df.describe()

df.isnull().sum()

df.dtypes

df['horsepower']=df['horsepower'].replace(to_replace='?',value=np.nan)

df.info()

df['horsepower']=df['horsepower'].astype(float)

df.info()

median1=df['horsepower'].median()

df['horsepower'].replace(np.nan,median1,inplace=True)

df.sample(10)

median1

df.drop("car name",axis=1,inplace=True)

df.head()

